from dotenv import load_dotenv
from twilio.rest import Client

twilio_client = Client()
load_dotenv()


def send_message(llm_output):
    """
    Sends a WhatsApp message using Twilio's API.

    Args:
        llm_output (str): The output generated by the Meta-Llama 3.1 model.

    Notes:
        replace the to="whatsapp:<>" with your phone number with country code.
    """
    twilio_client.messages.create(
        from_="whatsapp:+14155238886", body=llm_output, to="whatsapp:<>"
    )
